# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esp32shell_qt_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandlist = QtWidgets.QListWidget(self.centralwidget)
        self.commandlist.setGeometry(QtCore.QRect(30, 120, 231, 571))
        self.commandlist.setObjectName("commandlist")
        self.label_commandlist = QtWidgets.QLabel(self.centralwidget)
        self.label_commandlist.setGeometry(QtCore.QRect(30, 100, 161, 16))
        self.label_commandlist.setObjectName("label_commandlist")
        self.text_output = QtWidgets.QTextEdit(self.centralwidget)
        self.text_output.setGeometry(QtCore.QRect(290, 120, 581, 311))
        self.text_output.setObjectName("text_output")
        self.command_input = QtWidgets.QLineEdit(self.centralwidget)
        self.command_input.setGeometry(QtCore.QRect(30, 70, 841, 20))
        self.command_input.setObjectName("command_input")
        self.label_command_input = QtWidgets.QLabel(self.centralwidget)
        self.label_command_input.setGeometry(QtCore.QRect(30, 40, 111, 16))
        self.label_command_input.setObjectName("label_command_input")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(290, 100, 47, 13))
        self.label_output.setObjectName("label_output")
        self.ReplPane = MicroPythonREPLPane(self.centralwidget)
        self.ReplPane.setGeometry(QtCore.QRect(290, 460, 581, 231))
        self.ReplPane.setObjectName("ReplPane")
        self.label_repl = QtWidgets.QLabel(self.centralwidget)
        self.label_repl.setGeometry(QtCore.QRect(300, 440, 90, 16))
        self.label_repl.setObjectName("label_repl")
        self.radioButton_commandmode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_commandmode.setGeometry(QtCore.QRect(130, 40, 141, 20))
        self.radioButton_commandmode.setChecked(True)
        self.radioButton_commandmode.setObjectName("radioButton_commandmode")
        self.radioButton_replmode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_replmode.setGeometry(QtCore.QRect(270, 40, 121, 20))
        self.radioButton_replmode.setObjectName("radioButton_replmode")
        self.label_comport = QtWidgets.QLabel(self.centralwidget)
        self.label_comport.setGeometry(QtCore.QRect(30, 10, 441, 16))
        self.label_comport.setObjectName("label_comport")
        self.label_srcpath = QtWidgets.QLabel(self.centralwidget)
        self.label_srcpath.setGeometry(QtCore.QRect(380, 40, 81, 20))
        self.label_srcpath.setObjectName("label_srcpath")
        self.lineEdit_srcpath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_srcpath.setGeometry(QtCore.QRect(480, 40, 391, 20))
        self.lineEdit_srcpath.setObjectName("lineEdit_srcpath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_commandlist.setText(_translate("MainWindow", "Command list"))
        self.label_command_input.setText(_translate("MainWindow", "Command"))
        self.label_output.setText(_translate("MainWindow", "Output"))
        self.label_repl.setText(_translate("MainWindow", "Repl"))
        self.radioButton_commandmode.setText(_translate("MainWindow", "Command mode"))
        self.radioButton_replmode.setText(_translate("MainWindow", "REPL mode"))
        self.label_comport.setText(_translate("MainWindow", "COM: "))
        self.label_srcpath.setText(_translate("MainWindow", "Source path"))
from repl_gui import MicroPythonREPLPane
